# Generated by Django 6.0.6 on 2026-07-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='barrio',
            field=models.CharField(choices=[('PAL', 'Palermo'), ('STL', 'San Telmo'), ('REC', 'Recoleta'), ('BOC', 'La Boca')], default='PAL', max_length=3),
        ),
    ]
