# Generated by Django 6.0.6 on 2026-07-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_alter_cafe_options_alter_cafe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
