# Generated by Django 6.0.6 on 2026-07-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0004_cafe_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
