# Generated by Django 6.0.6 on 2026-07-07 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0005_barrio'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='communa',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
