# Generated by Django 6.0.6 on 2026-07-08 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0006_barrio_communa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='barrio_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cafes', to='cafes.barrio'),
        ),
    ]
