# Generated by Django 6.0.6 on 2026-07-08 17:46
from django.db import migrations

BARRIO_CODE_MAP = {
    'PAL': 'Palermo', 'STL': 'San Telmo', 'REC': 'Recoleta', 'BOC': 'La Boca',
}

def populate_barrio_fk(apps, schema_editor):
    Cafe = apps.get_model('cafes', 'Cafe')
    Barrio = apps.get_model('cafes', 'Barrio')
    for cafe in Cafe.objects.all():
        barrio_name = BARRIO_CODE_MAP.get(cafe.barrio)
        if barrio_name:
            barrio_obj, _ = Barrio.objects.get_or_create(name=barrio_name)
            cafe.barrio_fk = barrio_obj
            cafe.save()

def reverse_populate(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [('cafes', '0007_cafe_barrio_fk')]  # match your actual step-1 filename
    operations = [migrations.RunPython(populate_barrio_fk, reverse_populate)]
