# Generated by Django 6.0.6 on 2026-07-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0008_populate_barrio_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='barrio',
        ),
    ]
