# Generated by Django 6.0.6 on 2026-07-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0009_remove_cafe_barrio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='barrio_fk',
            new_name='barrio',
        ),
    ]
