# Generated by Django 6.0.6 on 2026-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0010_rename_barrio_fk_cafe_barrio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
