# Generated by Django 6.0.6 on 2026-07-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0011_cafe_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('join_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
